# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftui-firebase-connection' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftui-firebase-connection
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'swiftui-firebase-connectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftui-firebase-connectionUITests' do
    # Pods for testing
  end

end
